### ISSUE TITLE
Project refuses to build: Can't find GithubLoginButton.razor

### ISSUE THREAD

**Issue by PSCourtney** [acupofjose/supasharp-todo#1]
Trying to port this project to .NET 8 Web APP Auto mode and this login view of GitHubLoginButton causes the project to fall over. I even have build issues on this WASM version of the app saying that it can't find the component. 

![error](https://github.com/user-attachments/assets/7b053aec-138d-44f5-b8ae-8ff7ddc0a605)

Do you mind explaining this a bit to me? Cheers

Love your work. 👏

**Comment by acupofjose** [comment]
Hm.. not sure! I just did a full clean and pull on my computer and was able to get it up and running without any issue as a fresh project. 

You can see a fresh build process (which is currently deployed on github pages) here: https://github.com/acupofjose/supasharp-todo/blob/master/.github/workflows/publish_to_pages.yml

If it can't be found it is likely an import/path/globals issue. `GithubLoginButton` is in the `SupasharpTodo.BlazorWASM` project and injected as a dynamic component... Are you sure it's present in your new project?

**Comment by PSCourtney** [comment]
Ah I've found the `GithubLoginButton `code,  it's only found in the `SupasharpTodo.MauiBlazor` project! 

Now I just need to get WebAuthenticator working. Apologies for the nuisance issue!

**Comment by acupofjose** [comment]
No worries - good luck!
